##########################
##### HomeKit ############
##########################

# - alias: 'Start HomeKit'
#   trigger:
#     - platform: homeassistant
#       event: start
#   action:
#     - delay: 00:03  # Waits 3 minutes
#     - service: homekit.start

##########################
##### Harmony Remote #####
##########################

# - alias: Harmony Volume
  # trigger:
    # platform: state
    # entity_id: input_select.harmony_volume
  # action:
    # - service: remote.send_command
      # data_template:
        # entity_id: remote.harmony_hub
        # command: VolumeUp
        # device: 48124423

######### TODO-FIX ##############
- alias: Media - Remote external update input select
  trigger:
    - platform: state
      entity_id: remote.harmony_hub
  action:
    - delay: '00:00:20'
    - service: input_select.select_option
      data_template:
        entity_id: input_select.livingroomharmony
        option: states.remote.harmony_hub.attributes.current_activity
################################

- id: set_initial_values_on_harmony_start
  alias: "Set initial values on Harmony Start"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: remote.harmony_hub
    to: 'on'
  action:
    # - service: homeassistant.turn_on
      # entity_id: input_boolean.tv
    - service: input_select.select_option
      data_template:
        entity_id: input_select.livingroomharmony
        option: >
          {{ state_attr('remote.harmony_hub','current_activity') }}

- id: update_ha_if_harmony_activity_changes
  alias: "Update HA if Harmony activity changes"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.livingroomremote
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.livingroomharmony
        option: "{{trigger.to_state.state}}"

- alias: Media - Remote start activity from input select
  trigger:
    - platform: state
      entity_id: input_select.livingroomharmony
  action:
    - service: script.turn_on
      entity_id: script.input_select_harmony
