homeassistant:
  name: Waterfront Acres
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Indiana/Indianapolis
  # Include Packages
  packages: !include_dir_named packages

# Customization
  customize: !include includes/customize.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

panel_iframe:
  router:
    title: Router
    icon: mdi:router-wireless
    url: http://192.168.1.1

# Discover some devices automatically
#discovery:

# HomeKit
# homekit:
#   auto_start: false

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
recorder:

# View all events in a logbook
logbook: !include includes/logbook.yaml

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

# iOS App
ios:

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

media_extractor:

# Alexa
emulated_hue:
  expose_by_default: false
  entities:
    switch.ge_12722_onoff_relay_switch_switch:
      hidden: false
    light.ge_12724_3way_dimmer_switch_level:
      hidden: false
    light.ge_12730_fan_control_switch_level:
      hidden: false


# Cast
cast:

# Ecobee
ecobee:
  api_key: !secret ecobee_key
  hold_temp: True

# Harmony remote
remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.1.133

# Life360
device_tracker:
  - platform: life360
    username: !secret life360_user
    password: !secret life360_password
    interval_seconds: 10
    show_as_state: places, driving, moving
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_password

# Zwave
zwave:
  usb_path: /dev/ttyACM1
  network_key: !secret zwave_key
  autoheal: true

# Zones
zone:
  name: !secret zone_name
  latitude: !secret zone_latitude
  longitude: !secret zone_longitude
  radius: 200

# Single Files
group: !include includes/group.yaml
