resources:
  - url: /local/mini-media-player.js
    type: js
  - url: /local/thermostat-card/thermostat-card.js?v=1
    type: module
  - url: /local/entity-attributes-card/entity-attributes-card.js?v=1
    type: module

title: Waterfront Acres
views:
### Home ###
  - title: Home
    id: home
    icon: mdi:home-assistant
    badges:
        # - sensor.thermostat_temperature
    cards:
      - id: fe4fa24eb7594e2bbf803a1afc8a4efd  # Automatically created id
        type: vertical-stack
        cards:
          ### Switches ###
          - type: entities
            title: Switches
    #column_width: calc(100%/3)
            entities:
              - entity: light.recessed_lights # Recessed Light
                icon: mdi:ceiling-light
              - entity: light.fan # Fan Control
                icon: mdi:fan
              - entity: switch.fan_light # Fan Light
                icon: mdi:lightbulb
              - entity: switch.christmas_tree
                icon: mdi:pine-tree
              - entity: light.fastled_light
                icon: mdi:alarm-light
              # - entity: input_select.effects

          ### Devices ###
          - type: glance
            title: People
            show_name: false
            column_width: calc(100%/2)
            entities:
              - device_tracker.heather
              - device_tracker.justin_lewsader

          ## Favorites ###
          - type: glance
            title: Favorites
            id: favs
            column_width: calc(100%/3)
            entities:
              - entity: sensor.harmony_activity
                name: LR TV
                # tap_action: call-service
                # service: input_select.select_next
                # service_data:
                #   entity_id: input_select.harmony
              - entity: media_player.bedroom_directv
                name: BR TV
                icon: mdi:television
              - entity: media_player.kids_room_directv
                name: Kid's TV
                icon: mdi:television

          ## Scripts ###
          - type: glance
            id: scripts
            column_width: calc(100%/3)
            show_state: false
            entities:
              - entity: script.dinner_notify
                name: Dinner Announcement
                icon: mdi:food
                tap_action: call-service
                service: script.dinner_notify

      - id: 648dc34faa2c4d83a835333557c7ee83  # Automatically created id
        type: vertical-stack
        cards:
          ### Thermostat ###
          - type: glance
            entities:
              - lock.front_door
              - lock.back_door
          - type: glance
            show_state: false
            entities:
              - entity: binary_sensor.basement_center_water_sensor_opened
                name: Basement Center
                icon: mdi:water
              - entity: binary_sensor.basement_se_water_sensor_opened
                name: Basement SE
                icon: mdi:water
          ### Thermostat ###
          - type: entities
            entities:
              - entity: climate.thermostat
              - entity: sensor.thermostat_temperature
                name: Indoor Temp.
              - entity: sensor.weather_temperature
                name: Outdoor Temp.
              - entity: sensor.lil_bee_temperature
                name: Kid's Room Temp.
              - entity: sensor.thermostat_humidity
                name: Indoor Humidity
              - entity: sensor.weather_humidity
                name: Outdoor Humidity
          ### Forecast ###
          - type: weather-forecast
            entity: weather.forecast
### Camera ###
  - title: Cameras
    id: cameras
    icon: mdi:camera
    cards:
      - type: picture-glance
        title: Front Window
        entities: 
          - binary_sensor.front_window_motion_active
          - switch.front_window_night_vision
        camera_image: camera.front_window
      - type: history-graph
        title: Front Motion
        entities:
          - binary_sensor.front_window_motion_active
        hours_to_show: 12
### Media ###
  - title: Media
    id: media
    icon: mdi:television-classic
    cards:
      - id: 76c607b61a22458589b7a396639405ac  # Automatically created id
        type: vertical-stack
        cards:
          ### Living Room ###
          - type: entities
            title: Living Room
            entities:
              - entity: input_select.harmony
                name: Activities
              - entity: sensor.harmony_activity
              - entity: media_player.living_room_directv
                icon: mdi:television-box
                type: "custom:mini-media-player"
                group: true
              - type: custom:entity-attributes-card
                entity: media_player.living_room_directv
                filter:
                  include:
                    - key: media_player.living_room_directv.media_channel
                      name: Channel
                    - key: media_player.living_room_directv.media_title
                      name: Show
                    - key: media_player.living_room_directv.media_series_title
                      name: Title

            ### Master Bedroom ###
          - type: entities
            title: Master Bedroom
            entities:
              - entity: media_player.bedroom_directv
                icon: mdi:television-box
                type: "custom:mini-media-player"
                group: true
              - type: custom:entity-attributes-card
                entity: media_player.bedroom_directv
                filter:
                  include:
                    - key: media_player.bedroom_directv.media_channel
                      name: Channel
                    - key: media_player.bedroom_directv.media_title
                      name: Show
                    - key: media_player.bedroom_directv.media_series_title
                      name: Title


            ### Kids Room ###
          - type: entities
            title: Kid's Room
            entities:
              - entity: media_player.kids_room_directv
                icon: mdi:television-box
                type: "custom:mini-media-player"
                group: true
              - type: custom:entity-attributes-card
                entity: media_player.kids_room_directv
                filter:
                  include:
                    - key: media_player.kids_room_directv.media_channel
                      name: Channel
                    - key: media_player.kids_room_directv.media_title
                      name: Show
                    - key: media_player.kids_room_directv.media_series_title
                      name: Title

      - id: d093e7412766420dac371dfc7c75bb34  # Automatically created id
        type: entities
        title: Speakers
        entities:
          - media_player.kitchen_speaker
          - media_player.living_room__speaker
          - media_player.soundbar
          - media_player.googlehome0358
          - media_player.echo
          - media_player.dot

### Weather ###
  - title: Weather
    id: weather
    icon: mdi:weather-partlycloudy
    panel: true
    cards:
      - id: 0aaf3a08dec0468ca2da0be984ccf998  # Automatically created id
        type: iframe
        url: https://embed.windy.com/embed2.html?lat=40.044&lon=-86.572&zoom=6&level=surface&overlay=radar&menu=&message=true&marker=&calendar=12&pressure=&type=map&location=coordinates&detail=&detailLat=38.578&detailLon=-90.667&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1
        aspect_ratio: 100%


### Map ###
  - title: Map
    id: map
    icon: mdi:map-marker
    panel: true
    cards:
      - id: 24ba2b01c293434b812c4fc7e2a5ca33  # Automatically created id
        type: map
        default_zoom: 13
        entities:
          - device_tracker.justin_lewsader
          - device_tracker.heather
          - zone.home

### Sensors ###
  - title: Sensors
    id: Sensors
    icon: mdi:access-point
    cards:
      - id: b837069464fc4f04923a27e4dda659e1  # Automatically created id
        type: entities
        title: Leak Sensors
        entities:
          - entity: binary_sensor.basement_center_water_sensor_opened
            name: Basement - Center
            icon: mdi:water
          - entity: binary_sensor.basement_se_water_sensor_opened
            name: Basement - SE
            icon: mdi:water
