###############################################################################
#   @package        :   Harmony TV Activity Control
#   @description    :   Control Harmony TV Activities - No Longer Used
#   @url            :
###############################################################################

group:
  harmonytv:
    control: hidden
    name: Harmony Remote
    entities:
      - sensor.harmony_activity
      - input_select.harmony

input_select:
  harmony:
    name: Harmony Control
    options:
      - Select Activity
      - TV
      - Netflix
      - Xbox
      - Fire TV
      - Wii
      - Record Player
      - Power Off
    initial: Select Activity
    icon: mdi:remote

sensor:
  - platform: template
    sensors:
      harmony_activity:
        friendly_name: 'Harmony Activity'
        # value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        value_template: >-
          {% if is_state("states.remote.harmony_hub.attributes.current_activity", "PowerOff") %}
            Off
          {% elif is_state("states.remote.harmony_hub.attributes.current_activity", "TV") %}
            TV
          {% elif is_state("states.remote.harmony_hub.attributes.current_activity", "Netflix") %}
            Netflix
          {% elif is_state("states.remote.harmony_hub.attributes.current_activity", "Fire TV") %}
            Fire TV
          {% elif is_state("states.remote.harmony_hub.attributes.current_activity", "Xbox") %}
            Xbox
          {% elif is_state("states.remote.harmony_hub.attributes.current_activity", "Record Player") %}
            Record Player
          {% elif is_state("states.remote.harmony_hub.attributes.current_activity", "Wii") %}
            Wii
          {% else %}
            Unknown
          {% endif %}
        icon_template: >-
          {% if is_state("sensor.harmony_activity", "TV") %}
            mdi:television-classic
          {% elif is_state("sensor.harmony_activity", "Netflix") %}
            mdi:netflix
          {% elif is_state("sensor.harmony_activity", "Fire TV") %}
            mdi:amazon
          {% elif is_state("sensor.harmony_activity", "Xbox") %}
            mdi:xbox
          {% elif is_state("sensor.harmony_activity", "Record Player") %}
            mdi:record-player
          {% elif is_state("sensor.harmony_activity", "Wii") %}
            mdi:wii
          {% else %}
            mdi:television
          {% endif %}
###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: Start Harmony Activity
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.harmony
      from: 'Select Activity'
    action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "TV") %}
            22985196
          {% elif is_state("input_select.harmony", "Netflix") %}
            28656554
          {% elif is_state("input_select.harmony", "Xbox") %}
            22985907
          {% elif is_state("input_select.harmony", "Fire TV") %}
            36395736
          {% elif is_state("input_select.harmony", "Wii") %}
            36381527
          {% elif is_state("input_select.harmony", "Record Player") %}
            28806653
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Activity"

  - alias: Stop Harmony Activity
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'Power Off'
    action:
    - service: remote.turn_off
      entity_id: remote.harmony_hub
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Activity"
