###############################################################################
#   @package        :   Media Player
#   @description    :   
#   @url            :
###############################################################################
homeassistant:
  customize:

group:

input_number:

input_select:

###############################################################################
#                               Automations
###############################################################################
automation:

###############################################################################
#                               Scripts
###############################################################################
script:
  dinner_notify:
    sequence:
      - alias: Dinner Announcement
        service: tts.google_say
        data:
          message: 'Hey, it's dinner time!'
