###############################################################################
#   @package        :   Media Players
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:

group:
  google_home:
    name: Google Home Devices
    entities:
      - media_player.living_room__speaker
      - media_player.kitchen_speaker
      - media_player.googlehome0358

media_player:
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_password
    url: amazon.com
    # TODO
  # - platform: samsungtv
  #   host:
  #   name: Bedroom TV
  #   mac:

###############################################################################
#                               Automations
###############################################################################
automation:

###############################################################################
#                               Scripts
###############################################################################
script:
  dinner_notify:
    sequence:
      - alias: Dinner Announcement
        service: tts.google_say
        entity_id: group.google_home
        data:
          message: 'Dinner is ready!'
