###############################################################################
#   @package        :   Media Players
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:
    # Hide other Alexa account devices
    media_player.everywhere:
      hidden: true
    media_player.heathers_alexa_apps:
      hidden: true
    media_player.justins_alexa_apps:
      hidden: true
    media_player.justins_fire:
      hidden: true
    media_player.justins_fire_tv_stick:
      hidden: true
    media_player.this_device:
      hidden: true

group:
  google_home:
    name: Google Home Devices
    entities:
      - media_player.living_room__speaker
      - media_player.kitchen_speaker
      - media_player.googlehome0358
  echos:
    name: Echo Devices
    entities:
      - media_player.echo
      - media_player.dot

media_player:
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_password
    url: amazon.com
    # TODO Find IP & MAC addresses
  # - platform: samsungtv
  #   host:
  #   name: Bedroom TV
  #   mac:

###############################################################################
#                               Automations
###############################################################################
automation:

###############################################################################
#                               Scripts
###############################################################################
script:
  dinner_notify:
    sequence:
      - alias: Dinner Announcement
        service: tts.google_say
        entity_id: group.google_home
        data:
          message: 'Dinner is ready!'
  #REVIEW This works! Make group with Echo's & Google's, etc.
  alexa_test:
    sequence:
      # - alias: Dinner Announcement
        service: media_player.alexa_tts
        entity_id: media_player.echo
        data:
          message: 'This is a test of the Echo TTS service.'
  #TEMP Testing media_extractor script (radio station setup)
  radio_k105:
    sequence:
      - alias: Play K105
        service: media_extractor.play_media
        entity_id: media_player.living_room__speaker
        media_content_id: http://54.82.44.170/neuhoffcomm-wkoafmaac-ibc3
        media_content_type: music
