###############################################################################
#   @package        :   Media Players
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:

group:
  google_home:
    name: Google Home Devices
    entities:
      - media_player.living_room__speaker
      - media_player.kitchen_speaker
      - media_player.googlehome0358

media_player:
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_password
    url: amazon.com
    # TODO Find IP & MAC addresses
  # - platform: samsungtv
  #   host:
  #   name: Bedroom TV
  #   mac:

###############################################################################
#                               Automations
###############################################################################
automation:

###############################################################################
#                               Scripts
###############################################################################
script:
  dinner_notify:
    sequence:
      - alias: Dinner Announcement
        service: tts.google_say
        entity_id: group.google_home
        data:
          message: 'Dinner is ready!'
#REVIEW This works! Make group with Echo's & Google's, etc.
  alexa_test:
    sequence:
      # - alias: Dinner Announcement
        service: media_player.alexa_tts
        entity_id: media_player.echo
        data:
          message: 'This is a test of the Echo TTS service.'
