###############################################################################
#   @package        :   Media Player
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:

group:
  google_home:
    name: Google Home Devices
    entities:
      - media_player.living_room__speaker
      - media_player.kitchen_speaker
      - media_player.googlehome0358

###############################################################################
#                               Automations
###############################################################################
automation:

###############################################################################
#                               Scripts
###############################################################################
script:
  dinner_notify:
    sequence:
      - alias: Dinner Announcement
        service: tts.google_say
        entity_id: group.google_home
        data:
          message: 'Dinner is ready!'
