###############################################################################
#   @package        :   Switches
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:
    switch.ge_12722_onoff_relay_switch_switch:
      friendly_name: Fan Light

#group:

###############################################################################
#                               Scenes
###############################################################################
#scene:

###############################################################################
#                               Automations
###############################################################################
#automation:
