###############################################################################
#   @package        :   Switches
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:
    switch.ge_12722_onoff_relay_switch_switch:
      friendly_name: Fan Light
    light.ge_12724_3way_dimmer_switch_level:
      friendly_name: Recessed Lights
    # light.ge_12730_fan_control_switch_level:
    #   friendly_name: Fan
    fan.ge_12730_fan_control_switch_level:
      friendly_name: Fan
#group:

###############################################################################
#                               Scenes
###############################################################################
#scene:

###############################################################################
#                               Automations
###############################################################################
#automation:
