###############################################################################
#   @package        :   Switches
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:
    fan.ge_12730_fan_control_switch_level_2:
      friendly_name: Fan
      icon: mdi:fan
    switch.ge_12722_onoff_relay_switch_switch_2:
      friendly_name: Fan Light
      icon: mdi:lightbulb

#group:

###############################################################################
#                               Scenes
###############################################################################
#scene:

###############################################################################
#                               Automations
###############################################################################
#automation:
