###############################################################################
#   @package        :   Switches
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:
    light.fan:
      friendly_name: Fan
      icon: mdi:fan

#group:

###############################################################################
#                               Scenes
###############################################################################
#scene:

###############################################################################
#                               Automations
###############################################################################
#automation:
