###############################################################################
#   @package        :   weather
#   @description    : weather information
#   @url            :
###############################################################################
homeassistant:
  # customize:

# group:

sensor:
  - platform: darksky
    api_key: !secret darksky_key
    update_interval: '00:05:00'
    name: Weather
    monitored_conditions:
      - summary
#      - icon
#      - nearest_storm_distance
#      - nearest_storm_bearing
#      - precip_type
      - precip_intensity
#      - precip_probability
      - temperature
#      - apparent_temperature
#      - dew_point
#      - wind_speed
#      - wind_bearing
#      - cloud_cover
      - humidity
#      - pressure
      - visibility
#      - ozone
#      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
#      - apparent_temperature_max
#      - apparent_temperature_min
#      - precip_intensity_max

# weather:
#   - platform: darksky
#     name: Forecast
#     api_key: !secret darksky_key

weather:
  - platform: yweather
