###############################################################################
#   @package        :   Xbox
#   @description    :
#   @url            :
###############################################################################
homeassistant:
  customize:

group:

sensor:
  - platform: xbox_live
    api_key: !secret xbox_key
    xuid:
      - !secret xbox_account_1
      - !secret xbox_account_2

###############################################################################
#                               Automations
###############################################################################
automation:
